name = "news-trending-generator"
compatibility_date = "2025-11-21"

# If you're only using Pages UI (and not wrangler publish), account_id is optional.
account_id = "ad3e5dc932de1d6f00502baa1debbec1"

# Tell Cloudflare Pages where the built static site is located
pages_build_output_dir = ".vitepress/dist"

[build]
command = "npm run build"
